### ISSUE TITLE
add support LOAD httpfs and etc in the initial sql or custom sql 

### ISSUE THREAD

**Issue by YuriyGavrilov** [motherduckdb/duckdb-tableau-connector#12]
There will be nice to have all the things available in DBeaver duckdb as in Tableau DuckDb 

for example to use s3 or parquet file in the web 

<img width="629" alt="Снимок экрана 2024-08-08 в 11 56 32" src="https://github.com/user-attachments/assets/71bc6795-4ed4-46d7-9e5b-e0d3553ff6cd">

nb: Many thanks for making this taco and sign it.

**Comment by yurifal** [comment]
What's the problem, mein Hertz? ;-) 
Do everything in the Initial SQL.
<img width="1352" alt="Screenshot 2024-08-08 at 12 51 03" src="https://github.com/user-attachments/assets/97514a82-f0f0-4379-a9aa-c2b07651685e">

**Comment by YuriyGavrilov** [comment]
:) i thought I tried, but it seams not enough. Thx 🙏

**Comment by YuriyGavrilov** [comment]
testes, it is working @yurifal @elefeint thx 🙏
