### ISSUE TITLE
Tableau cannot open sqlite file on Mac M1

### ISSUE THREAD

**Issue by mikerkent** [motherduckdb/duckdb-tableau-connector#14]
Hello,

I'm trying to open a SQLite file via Tableau. I've installed the following:
```
~/Library/Tableau/Drivers/duckdb_jdbc-1.1.3.jar
~/Document/My Tableau Repository/Connectors/duckdb_jdbc-v1.1.0-signed.taco
```

The error being raised is:
```
IO Error: Extension "~/.duckdb/extensions/v1.1.3/osx_amd64/sqlite_scanner.duckdb_extension" not found. Extension "sqlite" is an existing extension. Install it first using "INSTALL sqlite".
Unable to connect to the DuckDB by MotherDuck server "local". Check that the server is running and that you have access privileges to the requested database.
Connector Class: duckdb_jdbc, Version: 1.1.0
```

Some troubleshooting steps I've tried are:
1. `brew install duckdb` locally, then open the file. I ran the `INSTALL sqlite; LOAD sqlite;` first and it loaded fine and I was able to operate on the db.
2. I used the INSTALL/LOAD steps as part of Initial SQL

There is one more observation that strikes me as odd: the path in the error is `osx_amd64`, while the path that actually exists is `osx_arm64` (arm instead of amd). I suspect the jar version may be somehow mis-identifying my mac as amd64 instead of arm64, but another part actually loads properly the sqlite drivers into arm64.

Please let me know if there is anything else I can try on my end to get this operational or further logs I can supply.

Thanks!

**Comment by yurifal** [comment]
What version of Tableau Desktop are you on?
The Apple Silicon native one is 2024.2+ (the arm64 installer).

**Comment by mikerkent** [comment]
2023.1.19, unfortunately this is the latest version compatible with the shared Tableau Server, so I wont be able to try 2024.2+ 😞

**Comment by yurifal** [comment]
You may want to attach the SQLite file to the :memory:

<img width="1352" alt="Screenshot 2024-12-19 at 02 02 31" src="https://github.com/user-attachments/assets/ca630c60-6f55-418b-9b02-a36ac17956ce" />

<img width="1352" alt="Screenshot 2024-12-19 at 02 02 47" src="https://github.com/user-attachments/assets/5101f11a-13fd-4e82-8b40-698a2ae735b5" />

**Comment by mikerkent** [comment]
Thanks! This approach unblocks me. Would you prefer closing this or leaving it open to resolve any primary issue in the other path?

**Comment by yurifal** [comment]
Close please
